// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package io.cratis.arc.samples.kotlin.chronicle

import io.cratis.arc.artifacts.ArcArtifactModule
import io.cratis.arc.chronicle.chronicle
import io.cratis.arc.generated.KotlinChronicleSpringBootSampleArcArtifactModule
import io.cratis.arc.queries.BlockingReadModelForCommandResolver
import io.cratis.arc.queries.ReadModelForCommandOwnership
import io.cratis.arc.results.ValidationResultReasons
import io.cratis.arc.testing.CommandScenario
import io.cratis.arc.testing.QueryScenario
import java.util.ServiceLoader
import kotlinx.coroutines.runBlocking
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertNull
import org.junit.jupiter.api.Test

/** Fast public-path contracts for the Kotlin-authored Chronicle sample. */
public class KotlinChronicleContractsTests {
    private val module = KotlinChronicleSpringBootSampleArcArtifactModule()

    @Test
    public fun `generated module is discovered and event commands have no client response`() = runBlocking {
        val discovered = ServiceLoader.load(ArcArtifactModule::class.java).toList()
        assertEquals(listOf(module.javaClass), discovered.map(Any::javaClass))

        val scenario = CommandScenario(module, CreateTask::class.java)
        scenario.execute(CreateTask("task-1", "First title"))
            .shouldSucceed()
            .shouldHaveNoResponse()

        val event = scenario.chronicle().shouldHaveAppendedEvent("task-1", TaskCreated::class.java)
        assertEquals("First title", event.title)
    }

    @Test
    public fun `rename injects current model and constructs an exact scope`() = runBlocking {
        val current = TaskView("task-1", "Tenant-local title", 7)
        val scenario = CommandScenario(module, RenameTask::class.java)
            .addReadModelResolver(FixedTaskViewResolver(current))
            .withTenant("tenant-a")

        scenario.execute(RenameTask("task-1", "Renamed title", 7))
            .shouldSucceed()
            .shouldHaveNoResponse()

        val event = scenario.chronicle().shouldHaveAppendedEvent("task-1", TaskRenamed::class.java)
        assertEquals(TaskRenamed("Tenant-local title", "Renamed title"), event)
        val response = RenameTask("task-1", "Renamed title", 7).handle(current)
        assertEquals(7, response.concurrencyScopes.getValue("task-1").sequenceNumber.value)
    }

    @Test
    public fun `missing current model is dependency unavailable and appends nothing`() = runBlocking {
        val scenario = CommandScenario(module, RenameTask::class.java)
            .addReadModelResolver(FixedTaskViewResolver(null))
            .withTenant("tenant-a")

        val result = scenario.execute(RenameTask("missing", "Renamed title", 0))
        assertEquals(
            ValidationResultReasons.DEPENDENCY_UNAVAILABLE,
            result.result.validationResults.single().reason
        )
        assertNull(result.result.response)
        scenario.chronicle().shouldHaveNoAppendedEvents()
    }

    @Test
    public fun `generated by id and all query performers use captured tenant namespace`() = runBlocking {
        val expected = TaskView("task-1", "Projected title", 2)
        val reader = CapturingTaskViewReader(expected)
        val byId = module.queryPerformers.single { it.fullyQualifiedName.value.endsWith(".byId") }
        val all = module.queryPerformers.single { it.fullyQualifiedName.value.endsWith(".all") }

        QueryScenario<TaskView>(byId)
            .addService(TaskViewReader::class.java, reader)
            .withTenant("tenant-a")
            .perform(mapOf("id" to "task-1"))
            .shouldSucceed()
            .shouldHaveData(expected)

        QueryScenario<List<TaskView>>(all)
            .addService(TaskViewReader::class.java, reader)
            .withTenant("tenant-a")
            .perform()
            .shouldSucceed()
            .shouldHaveData(listOf(expected))

        assertEquals(listOf("tenant-a:task-1", "tenant-a:*"), reader.calls)
    }

    private class FixedTaskViewResolver(private val value: TaskView?) : BlockingReadModelForCommandResolver {
        override fun readModelTypes(): Set<Class<*>> = setOf(TaskView::class.java)
        override fun ownership(): ReadModelForCommandOwnership = ReadModelForCommandOwnership.DECLARED
        override fun resolveBlocking(
            readModelType: Class<*>,
            commandContext: io.cratis.arc.commands.CommandContext,
            key: Any
        ): Any? = value
    }

    private class CapturingTaskViewReader(private val value: TaskView) : TaskViewReader {
        val calls: MutableList<String> = mutableListOf()

        override suspend fun byId(namespace: String, id: String): TaskView {
            calls.add("$namespace:$id")
            return value
        }

        override suspend fun all(namespace: String): List<TaskView> {
            calls.add("$namespace:*")
            return listOf(value)
        }
    }
}
