# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
      time: "06:00"
      timezone: "Etc/UTC"
    labels:
      - dependencies
      - no-release
    open-pull-requests-limit: 10
    groups:
      gradle-non-major:
        update-types:
          - minor
          - patch

  - package-ecosystem: npm
    directory: "/ContractTests/TypeScript"
    schedule:
      interval: daily
      time: "06:15"
      timezone: "Etc/UTC"
    labels:
      - dependencies
      - no-release
    open-pull-requests-limit: 10
    groups:
      npm-non-major:
        update-types:
          - minor
          - patch
