// @generated by Cratis. Source: differential.fixture.commands.CreateFixtures
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command, CommandValidator } from "@cratis/arc/commands";
import {
    useCommand,
    type SetCommandValues,
    type ClearCommandValues,
} from "@cratis/arc.react/commands";
import { PropertyDescriptor } from "@cratis/arc/reflection";
import { FixtureModel } from "../Models/FixtureModel";
import type { FixtureState } from "../Models/FixtureState";

export interface ICreateFixtures {
    fixtureId?: string;
    states?: FixtureState[];
}

export class CreateFixturesValidator extends CommandValidator<ICreateFixtures> {
    constructor() {
        super();
        this.ruleFor((c) => c.fixtureId).notEmpty();
        this.ruleFor((c) => c.states).notEmpty();
    }
}

export class CreateFixtures
    extends Command<ICreateFixtures, FixtureModel>
    implements ICreateFixtures
{
    readonly route: string = "/api/commands/create-fixtures";
    readonly validation: CommandValidator = new CreateFixturesValidator();
    readonly treatWarningsAsErrors: boolean = true;
    readonly roles: string[] = ["creator", "admin"];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor("fixtureId", String, false),
        new PropertyDescriptor("states", Number, false),
    ];

    private _fixtureId!: string;
    private _states!: FixtureState[];

    constructor() {
        super(FixtureModel, true);
    }

    get requestParameters(): string[] {
        return [];
    }

    get fixtureId(): string {
        return this._fixtureId;
    }

    set fixtureId(value: string) {
        this._fixtureId = value;
        this.propertyChanged("fixtureId");
    }
    get states(): FixtureState[] {
        return this._states;
    }

    set states(value: FixtureState[]) {
        this._states = value;
        this.propertyChanged("states");
    }

    static use(
        initialValues?: ICreateFixtures,
    ): [CreateFixtures, SetCommandValues<ICreateFixtures>, ClearCommandValues] {
        return useCommand<CreateFixtures, ICreateFixtures>(
            CreateFixtures,
            initialValues,
        );
    }
}
