#!/usr/bin/env bash
# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
#
# Reproducibly captures the expected side of the .NET-derived proxy differential.
#
# Everything it needs comes from published NuGet packages at pinned versions. It never reads, builds or copies
# from a sibling Arc .NET checkout, so the result does not depend on an unrecorded local working tree.
#
#   ./capture.sh [output-directory]
#
# Writes the captured TypeScript plus capture-manifest.json, which records the pinned versions, the resolved
# SDK and runtime, and a SHA-256 for every captured file.

set -euo pipefail

ARC_VERSION="22.14.0"
PROXY_GENERATOR_VERSION="22.14.0"

script_directory="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
# Deliberately NOT ../dotnet. That directory holds the older hand-prepared fixture the differential gate still
# compares against; overwriting it from here would silently replace a reviewed expected side.
output_directory="${1:-$script_directory/../captured}"
work_directory="$(mktemp -d)"
trap 'rm -rf "$work_directory"' EXIT

export DOTNET_CLI_TELEMETRY_OPTOUT=1
export DOTNET_NOLOGO=1

command -v dotnet >/dev/null || { echo "dotnet is required on PATH." >&2; exit 1; }

echo "Capturing Arc .NET proxies"
echo "  Cratis.Arc:                 $ARC_VERSION"
echo "  Cratis.Arc.ProxyGenerator:  $PROXY_GENERATOR_VERSION"
echo "  dotnet SDK:                 $(dotnet --version)"

mkdir -p "$work_directory/src"
cp "$script_directory/Fixture.csproj" "$script_directory/Fixture.cs" "$work_directory/src/"

dotnet tool install Cratis.Arc.ProxyGenerator \
    --version "$PROXY_GENERATOR_VERSION" \
    --tool-path "$work_directory/tools" >/dev/null

# Publish rather than build: the generator reads the fixture through a MetadataLoadContext that resolves
# references from the assembly's own directory, so every dependency has to sit beside it.
dotnet publish "$work_directory/src/Fixture.csproj" \
    -c Release -o "$work_directory/publish" -v quiet --nologo >/dev/null

rm -rf "$work_directory/raw"
"$work_directory/tools/proxygenerator" \
    "$work_directory/publish/Arc.Kotlin.Differential.Fixture.dll" \
    "$work_directory/raw" \
    0 >"$work_directory/generator.log" 2>&1 || { cat "$work_directory/generator.log" >&2; exit 1; }

# The one normalization applied, and it is applied to .NET output only:
#
# The Arc .NET generator stamps a wall-clock `Time:` field into every generated header. The JVM generator
# emits no such field. Capturing it verbatim would make this fixture differ from itself on every run, which is
# exactly what stopped the previous fixture from being reproducible. It is removed here, at capture time, in a
# recorded step - not hidden inside a comparison that silently rewrites output later.
#
# Nothing else is transformed, and nothing whatsoever is applied to JVM output.
normalized=0
while IFS= read -r -d '' file; do
    perl -0pi -e 's/(\/\/ \@generated by Cratis\. Source: [^.]*(?:\.[^.]*)*?)\. Time: [^.]*\.[0-9]+Z(\. Hash: )/$1$2/g' "$file"
    normalized=$((normalized + 1))
done < <(find "$work_directory/raw" -type f -name '*.ts' -print0)

rm -rf "$output_directory"
mkdir -p "$output_directory"
cp -R "$work_directory/raw/." "$output_directory/"

python3 - "$output_directory" "$ARC_VERSION" "$PROXY_GENERATOR_VERSION" "$(dotnet --version)" <<'PY'
import hashlib, json, pathlib, sys

output, arc, generator, sdk = pathlib.Path(sys.argv[1]), sys.argv[2], sys.argv[3], sys.argv[4]
files = sorted(p for p in output.rglob('*') if p.is_file() and p.name != 'capture-manifest.json')
manifest = {
    'formatVersion': 1,
    'packages': {'Cratis.Arc': arc, 'Cratis.Arc.ProxyGenerator': generator},
    'dotnetSdk': sdk,
    'normalizations': [
        'Removed the generator wall-clock "Time:" header field, which the JVM generator does not emit.'
    ],
    'files': {
        str(p.relative_to(output)): hashlib.sha256(p.read_bytes()).hexdigest().upper()
        for p in files
    },
}
(output / 'capture-manifest.json').write_text(json.dumps(manifest, indent=2, sort_keys=True) + '\n')
print(f"Captured {len(files)} files into {output}")
PY

echo "  Normalized headers in $normalized files"
