#!/usr/bin/env python3
# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.
"""New, provenance-bearing captures only. No checkout of Arc .NET is consulted."""

import argparse
import base64
import ctypes
import datetime
import hashlib
import json
import os
from pathlib import Path
import platform
import re
import shutil
import stat
import subprocess
import sys
import tempfile
import urllib.request
import zipfile

HERE = Path(__file__).resolve().parent
REPO = HERE.parents[5]
INPUTS = ("Fixture.cs", "Fixture.csproj", "global.json", "NuGet.Config",
          "packages.lock.json", "packages.sha256.json", "tool.lock.json", "capture.sh", "capture.py")
MARKER = b"// @generated by Cratis"
HEADER = re.compile(
    rb"\A// @generated by Cratis\. Source: ([A-Za-z_][A-Za-z0-9_.+`]*)\. Time: "
    rb"(\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{7}Z)\. Hash: ([A-F0-9]{64})\n")
NORMALIZATION = "first-line-utc-time-removal-v1"


def sha256(data):
    return hashlib.sha256(data).hexdigest().upper()


def require_checksum(data, expected, algorithm="sha256"):
    actual = (sha256(data) if algorithm == "sha256" else
              base64.b64encode(hashlib.sha512(data).digest()).decode("ascii"))
    if actual != expected:
        raise ValueError(f"{algorithm} checksum mismatch: expected {expected}, got {actual}")


def normalize(data, relative):
    """Remove exactly one anchored timestamp, after verifying the untouched body hash."""
    data.decode("utf-8")  # Reject invalid UTF-8; never replace bytes.
    if relative.name == "index.ts":
        # Only pristine generator index exports may be headerless, not arbitrary manual files.
        if not re.fullmatch(rb"(?:export \* from '[A-Za-z0-9_./-]+';\n)+", data):
            raise ValueError(f"Unrecognized headerless index: {relative}")
        return data
    match = HEADER.match(data)
    if not match or data.count(MARKER) != 1:
        raise ValueError(f"Expected exactly one first-line generated header: {relative}")
    datetime.datetime.strptime(match[2].decode()[:19], "%Y-%m-%dT%H:%M:%S")
    body = data[match.end():]
    require_checksum(body, match[3].decode())
    return (MARKER + b". Source: " + match[1] + b". Hash: " + match[3] + b"\n" + body)


def no_symlinks(path):
    """Check the lexical path before resolve(), including dangling links and ancestors."""
    path = Path(os.path.abspath(path))
    for part in (*reversed(path.parents), path):
        if part.is_symlink():
            raise ValueError(f"Symlink refused: {part}")
    return path


def destination(path, root):
    path, root = no_symlinks(path), no_symlinks(root)
    if not path.is_relative_to(root) or path == root:
        raise ValueError(f"Capture must be a new child of {root}")
    if path.exists():
        raise ValueError(f"Existing destination refused (including owned captures): {path}")
    if not path.parent.is_dir():
        raise ValueError("Destination parent must already exist")
    return path


def inventory(root):
    result = {}
    for path in sorted(root.rglob("*")):
        if path.is_symlink() or not (path.is_dir() or path.is_file()):
            raise ValueError(f"Non-regular capture entry: {path}")
        if path.is_file():
            result[path.relative_to(root).as_posix()] = sha256(path.read_bytes())
    return result


def publish(stage, output, root):
    """Atomically publish without replacement, including an empty directory raced into place.

    POSIX rename alone can replace an unrelated empty directory. Refuse unsupported hosts
    rather than weakening this contract. This is not a sandbox against hostile ancestor swaps.
    """
    output = destination(output, root)
    libc = ctypes.CDLL(None, use_errno=True)
    if sys.platform == "darwin":
        call = libc.renamex_np
        call.argtypes = [ctypes.c_char_p, ctypes.c_char_p, ctypes.c_uint]
        args = (os.fsencode(stage), os.fsencode(output), 4)  # RENAME_EXCL
    elif sys.platform.startswith("linux") and hasattr(libc, "renameat2"):
        call = libc.renameat2
        call.argtypes = [ctypes.c_int, ctypes.c_char_p, ctypes.c_int, ctypes.c_char_p, ctypes.c_uint]
        args = (-100, os.fsencode(stage), -100, os.fsencode(output), 1)  # RENAME_NOREPLACE
    else:
        raise ValueError("Atomic no-replace publication requires macOS or Linux renameat2")
    call.restype = ctypes.c_int
    if call(*args) != 0:
        error = ctypes.get_errno()
        raise OSError(error, os.strerror(error), str(output))


def prepare(raw, stage, metadata, inputs):
    """All validation/writing is private; the destination is published only after this succeeds."""
    files = inventory(raw)
    if not files or not any(Path(name).name != "index.ts" for name in files):
        raise ValueError("Generator emitted no proxies")
    for name in files:
        if Path(name).suffix != ".ts":
            raise ValueError(f"Unexpected generator output: {name}")
        data = (raw / name).read_bytes()
        normalized = normalize(data, Path(name))
        for directory, content in (("raw", data), ("normalized", normalized)):
            target = stage / directory / name
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(content)
    for name in INPUTS:
        target = stage / "inputs" / name
        target.parent.mkdir(exist_ok=True)
        shutil.copyfile(inputs / name, target)
    manifest = dict(metadata, formatVersion=2, owner="arc-kotlin-dotnet-capture",
                    normalization=NORMALIZATION,
                    inputHashes=inventory(stage / "inputs"),
                    normalizedFiles=inventory(stage / "normalized"),
                    rawFiles=inventory(stage / "raw"), files=inventory(stage))
    (stage / "capture-manifest.json").write_text(
        json.dumps(manifest, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    verify_capture(stage)


def verify_capture(root):
    """Verify the exact inventory and rederive normalized bytes; hashes are not signatures."""
    root = no_symlinks(root)
    actual = inventory(root)
    manifest = json.loads((root / "capture-manifest.json").read_text(encoding="utf-8"))
    if (manifest["formatVersion"] != 2 or manifest["owner"] != "arc-kotlin-dotnet-capture"
            or manifest["normalization"] != NORMALIZATION):
        raise ValueError("Unsupported capture provenance")
    del actual["capture-manifest.json"]
    if actual != manifest["files"]:
        raise ValueError("Capture inventory/checksum mismatch")
    for directory, field in (("inputs", "inputHashes"), ("raw", "rawFiles"),
                             ("normalized", "normalizedFiles")):
        if inventory(root / directory) != manifest[field]:
            raise ValueError(f"{field} mismatch")
    if set(manifest["inputHashes"]) != set(INPUTS):
        raise ValueError("Input inventory mismatch")
    if not manifest["rawFiles"] or set(manifest["rawFiles"]) != set(manifest["normalizedFiles"]):
        raise ValueError("Raw/normalized inventory mismatch")
    for name in manifest["rawFiles"]:
        if normalize((root / "raw" / name).read_bytes(), Path(name)) != (root / "normalized" / name).read_bytes():
            raise ValueError(f"Normalization mismatch: {name}")
    return manifest


def run(args, work, env):
    print("+ " + " ".join(map(str, args)), flush=True)
    result = subprocess.run(list(map(str, args)), cwd=work, env=env, check=True,
                            stdout=subprocess.PIPE, stderr=subprocess.STDOUT, timeout=180)
    text = result.stdout.decode("utf-8")
    print(text, end="", flush=True)
    return text.strip()


def extract_tool(archive, tools):
    # The published tool bundles its complete dependency graph. The archive SHA-256 locks it all.
    with zipfile.ZipFile(archive) as package:
        prefix = "tools/net10.0/any/"
        count = 0
        for entry in package.infolist():
            if not entry.filename.startswith(prefix) or entry.is_dir():
                continue
            relative = Path(entry.filename[len(prefix):])
            if (relative.is_absolute() or ".." in relative.parts or "\\" in str(relative)
                    or stat.S_ISLNK(entry.external_attr >> 16)):
                raise ValueError("Unsafe tool archive member")
            target = tools / relative
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(package.read(entry))
            count += 1
        if not count or not (tools / "Cratis.Arc.ProxyGenerator.dll").is_file():
            raise ValueError("Missing net10.0 tool payload")


def verify_package(archive, checksum):
    """Validate signed archive bytes separately from NuGet's logical contentHash.

    Also verify extracted payload bytes: locked restore may reuse an existing package cache.
    NuGet intentionally does not extract OPC container metadata.
    """
    require_checksum(archive.read_bytes(), checksum)
    with zipfile.ZipFile(archive) as package:
        for entry in package.infolist():
            name = entry.filename
            if (entry.is_dir() or name in ("_rels/.rels", "[Content_Types].xml")
                    or name.startswith("package/services/metadata/core-properties/")):
                continue
            relative = Path(name)
            if relative.is_absolute() or ".." in relative.parts or "\\" in name:
                raise ValueError("Unsafe package archive member")
            file = no_symlinks(archive.parent / relative)
            # NuGet lowercases the nuspec filename on extraction.
            if relative.suffix == ".nuspec":
                file = no_symlinks(archive.parent / name.lower())
            if not file.is_file() or file.read_bytes() != package.read(entry):
                raise ValueError(f"Extracted package payload mismatch: {file}")


def runtime_evidence(log, runtime):
    """The generator's MetadataLoadContext selects references independently of the host."""
    evidence = {}
    for label, framework in (("Runtime", "Microsoft.NETCore.App"),
                             ("AspNetCoreApp", "Microsoft.AspNetCore.App")):
        matches = re.findall(r"^  " + label + r" assemblies: (.+)$", log, re.M)
        if len(matches) != 1 or Path(matches[0]).parts[-2:] != (framework, runtime):
            raise ValueError(f"Generator did not resolve pinned {framework} {runtime}")
        evidence[framework] = runtime
    return evidence


def capture(output):
    root = REPO / ".ai-work"
    output = destination(output, root)
    managed = os.environ.get("AI_WORK_OUTPUT")
    if not managed:
        raise ValueError("Run through ai-work-lifecycle run-task (AI_WORK_OUTPUT is required)")
    managed = no_symlinks(managed)
    if not managed.is_relative_to(root) or not managed.is_dir():
        raise ValueError("AI_WORK_OUTPUT must be an existing managed directory under .ai-work")
    # No recursive deletion here. Lifecycle owns disposable outputs, including failures.
    work = Path(tempfile.mkdtemp(prefix="capture-", dir=managed))
    source = work / "source"
    source.mkdir()
    for name in INPUTS:
        shutil.copyfile(HERE / name, source / name)
    # Do not inherit MSBuild/NuGet/host injection settings, project references, local tools,
    # or repository/global NuGet configuration. Share the standard NuGet package cache only.
    env = {key: os.environ[key] for key in ("HOME", "PATH", "SystemRoot") if key in os.environ}
    env.update(DOTNET_CLI_TELEMETRY_OPTOUT="1", DOTNET_NOLOGO="1", DOTNET_MULTILEVEL_LOOKUP="0",
               DOTNET_CLI_WORKLOAD_UPDATE_NOTIFY_DISABLE="1", DOTNET_CLI_HOME=str(work / "cli-home"),
               NUGET_PACKAGES=str(Path.home() / ".nuget/packages"),
               TMPDIR=str(work), LANG="C.UTF-8", LC_ALL="C.UTF-8", TZ="UTC")
    sdk = json.loads((source / "global.json").read_text())["sdk"]["version"]
    tool = json.loads((source / "tool.lock.json").read_text())
    dotnet = shutil.which("dotnet")
    if not dotnet:
        raise ValueError("dotnet is required on PATH")
    if run([dotnet, "--version"], source, env) != sdk:
        raise ValueError("Resolved SDK does not match global.json")
    runtimes = run([dotnet, "--list-runtimes"], source, env)
    selected = {}
    for framework in ("Microsoft.NETCore.App", "Microsoft.AspNetCore.App"):
        matches = re.findall(r"^" + re.escape(framework + " " + tool["runtime"]) + r" \[(.+)\]$", runtimes, re.M)
        if len(matches) != 1:
            raise ValueError(f"Exactly one installed {framework} {tool['runtime']} is required")
        selected[framework] = tool["runtime"]
    archive = work / "generator.nupkg"
    with urllib.request.urlopen(tool["url"], timeout=60) as response:
        data = response.read()
    require_checksum(data, tool["sha256"])
    archive.write_bytes(data)
    tools = work / "tools"
    extract_tool(archive, tools)
    properties = ["-p:ImportDirectoryBuildProps=false", "-p:ImportDirectoryBuildTargets=false",
                  "-p:ImportDirectoryPackagesProps=false", "-p:UseSharedCompilation=false"]
    run([dotnet, "restore", source / "Fixture.csproj", "--locked-mode", "--configfile",
         source / "NuGet.Config", *properties], source, env)
    if (source / "packages.lock.json").read_bytes() != (HERE / "packages.lock.json").read_bytes():
        raise ValueError("Restore changed the committed dependency lock")
    assets = json.loads((source / "obj/project.assets.json").read_text())
    package_roots = [Path(path) for path in assets["packageFolders"]]
    if package_roots != [Path(env["NUGET_PACKAGES"])]:
        raise ValueError("Unexpected restore package folder")
    if set(assets["project"]["restore"]["sources"]) != {"https://api.nuget.org/v3/index.json"}:
        raise ValueError("Unexpected NuGet source")
    lock = json.loads((source / "packages.lock.json").read_text())
    expected_libraries = {f"{name}/{dependency['resolved']}" for name, dependency
                          in lock["dependencies"]["net10.0"].items()}
    if (set(assets["libraries"]) != expected_libraries
            or any(item["type"] != "package" for item in assets["libraries"].values())):
        raise ValueError("Restore graph differs from the package-only lock")
    archive_hashes = json.loads((source / "packages.sha256.json").read_text())
    expected_archives = set()
    for name, dependency in lock["dependencies"]["net10.0"].items():
        relative = (Path(name.lower()) / dependency["resolved"].lower()
                    / f"{name.lower()}.{dependency['resolved'].lower()}.nupkg")
        expected_archives.add(relative.as_posix())
        found = [p / relative for p in package_roots if (p / relative).is_file()]
        if len(found) != 1:
            raise ValueError(f"Cannot uniquely verify restored package: {name}")
        verify_package(found[0], archive_hashes[relative.as_posix()])
    if expected_archives != set(archive_hashes):
        raise ValueError("Archive checksum inventory differs from dependency lock")
    run([dotnet, "publish", source / "Fixture.csproj", "--no-restore", "-c", "Release",
         "-o", work / "publish", "-v", "quiet", *properties], source, env)
    raw = work / "raw"
    generator_log = run([dotnet, "exec", "--fx-version", tool["runtime"], "--roll-forward", "Disable",
                         tools / "Cratis.Arc.ProxyGenerator.dll",
                         work / "publish/Arc.Kotlin.Differential.Fixture.dll", raw, "0"], source, env)
    observed_runtimes = runtime_evidence(generator_log, tool["runtime"])
    (work / "generator.log").write_text(generator_log + "\n", encoding="utf-8")
    stage = work / "staged"
    stage.mkdir()
    metadata = {"packages": {"Cratis.Arc": "22.14.0", tool["package"]: tool["version"]},
                "dotnetSdk": sdk, "dotnetRuntimes": selected,
                "generatorObservedRuntimes": observed_runtimes,
                "dotnetExecutableSha256": sha256(Path(dotnet).read_bytes()),
                "runtimeSelection": "dotnet exec --fx-version " + tool["runtime"] + " --roll-forward Disable",
                "platform": {"system": platform.system(), "architecture": platform.machine()},
                "toolArchiveSha256": tool["sha256"], "lockedRestore": True,
                "dependencyArchiveAndPayloadHashesVerified": True,
                "generatorArguments": ["Arc.Kotlin.Differential.Fixture.dll", "raw", "0"]}
    prepare(raw, stage, metadata, source)
    publish(stage, output, root)
    print(f"Captured and verified {len(inventory(output / 'normalized'))} files into {output}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument("--output", type=Path, help="new directory under repository .ai-work; never overwritten")
    group.add_argument("--verify", type=Path, help="verify capture inventory and exact normalization")
    args = parser.parse_args()
    try:
        if args.verify:
            verify_capture(args.verify)
            print("Capture inventory and normalization verified")
        else:
            capture(args.output)
    except subprocess.CalledProcessError as error:
        print(error.stdout.decode("utf-8", errors="replace"), file=sys.stderr)
        return 1
    except (ValueError, OSError, KeyError, subprocess.TimeoutExpired) as error:
        print(f"Capture refused/failed: {error}", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
