// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package io.cratis.arc.gradle

import java.io.File
import java.security.MessageDigest
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.BeforeEach
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

internal class CapturedProxyContractTest {
    @TempDir
    lateinit var work: File
    private lateinit var captured: File
    private lateinit var actual: File
    private val capturedPath = "Arc/Kotlin/Differential/Fixture"
    private val actualPath = "arc/kotlin/differential/fixture"

    @BeforeEach
    fun prepare() {
        val resource = requireNotNull(javaClass.getResource("/differential/captured/capture-manifest.json"))
        captured = work.resolve("captured")
        File(resource.toURI()).parentFile.copyRecursively(captured)
        actual = work.resolve("actual")
        captured.resolve(capturedPath).walkTopDown().filter { it.isFile }.forEach { file ->
            val target = actual.resolve("$actualPath/${file.relativeTo(captured.resolve(capturedPath)).invariantSeparatorsPath}")
            target.parentFile.mkdirs()
            val text = file.readText().replace("Arc.Kotlin.Differential.Fixture.", "arc.kotlin.differential.fixture.")
                .replace("OrderView.AllOrders'", "OrderView.allOrders'")
                .replace("OrderView.OrderById'", "OrderView.orderById'")
            target.writeText(text)
            if (file.name != "index.ts") rehash(target)
        }
        // Test input only: capability-free JVM List query. The production helper owns a separate literal oracle.
        val allOrders = actual.resolve("$actualPath/AllOrders.ts")
        allOrders.writeText("// @generated by Cratis. Source: arc.kotlin.differential.fixture.OrderView. Hash: pending\n" + """
            import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
            import { useQuery, useSuspenseQuery, type PerformQuery, QueryWhen } from '@cratis/arc.react/queries';
            import { ParameterDescriptor } from '@cratis/arc/reflection';
            import { OrderView } from './OrderView';
            export class AllOrders extends QueryFor<OrderView[]> {
                readonly route: string = '/api/arc/kotlin/differential/fixture/all-orders';
                readonly queryName: string = 'arc.kotlin.differential.fixture.OrderView.allOrders';
                readonly treatWarningsAsErrors: boolean = false;
                readonly roles: string[] = [];
                readonly defaultValue: OrderView[] = [];
                constructor() { super(OrderView, true); }
                get requiredRequestParameters(): string[] { return []; }
                readonly parameterDescriptors: ParameterDescriptor[] = [];
                static use(): [QueryResultWithState<OrderView[]>, PerformQuery] {
                    const [result, perform] = useQuery<OrderView[], AllOrders>(AllOrders, undefined);
                    return [result, perform];
                }
                static useSuspense(): [QueryResultWithState<OrderView[]>, PerformQuery] {
                    const [result, perform] = useSuspenseQuery<OrderView[], AllOrders>(AllOrders, undefined);
                    return [result, perform];
                }
                static when(condition: boolean): QueryWhen<AllOrders, OrderView[]> {
                    return new QueryWhen<AllOrders, OrderView[]>(AllOrders, condition);
                }
            }
        """.trimIndent() + "\n")
        rehash(allOrders)
    }

    @Test
    fun `captured and JVM-shaped inputs independently satisfy the bounded oracle`() {
        CapturedProxyContract.verify(captured, actual)
    }

    @Test
    fun `known import syntax and property ordering differences are allowed without byte preparation`() {
        val command = actual.resolve("$actualPath/PlaceOrder.ts")
        var text = command.readText()
        text = replaceOnce(text, "import { Guid } from '@cratis/fundamentals';\nimport { DateOnly } from '@cratis/fundamentals';\nimport { TimeOnly } from '@cratis/fundamentals';",
            "import { DateOnly, Guid, TimeOnly } from '@cratis/fundamentals';")
        text = replaceOnce(text, "import { OrderKind } from './OrderKind';", "import type { OrderKind } from './OrderKind';")
        text = replaceOnce(text, "useCommand, SetCommandValues, ClearCommandValues", "useCommand, type SetCommandValues, type ClearCommandValues")
        text = replaceOnce(text, "    customer?: string;\n    express?: boolean;", "    express?: boolean;\n    customer?: string;")
        text = replaceOnce(text, "        new PropertyDescriptor('customer', String, false),\n        new PropertyDescriptor('express', Boolean, false),",
            "        new PropertyDescriptor('express', Boolean, false),\n        new PropertyDescriptor('customer', String, false),")
        command.writeText(text)
        rehash(command)
        CapturedProxyContract.verify(captured, actual)
    }

    @Test
    fun `changed command and query routes fail even with valid body checksums`() {
        listOf("PlaceOrder.ts" to "place-order", "AllOrders.ts" to "all-orders", "OrderById.ts" to "order-by-id")
            .forEach { (file, route) ->
                rejectsActual(file, "/api/arc/kotlin/differential/fixture/$route", "/api/wrong/$route")
            }
    }

    @Test
    fun `changed field and parameter types fail`() {
        rejectsActual("PlaceOrder.ts", "quantity?: number;", "quantity?: string;")
        rejectsActual("OrderView.ts", "requestedDate!: DateOnly;", "requestedDate!: string;")
        rejectsActual("OrderById.ts", "id: Guid;", "id: string;")
    }

    @Test
    fun `changed response collection flags fail`() {
        rejectsActual("AllOrders.ts", "super(OrderView, true);", "super(OrderView, false);")
        rejectsActual("OrderById.ts", "super(OrderView, false);", "super(OrderView, true);")
        rejectsActual("PlaceOrder.ts", "super(Guid, false);", "super(Guid, true);")
    }

    @Test
    fun `changed response property parameter and model constructors fail`() {
        rejectsActual("PlaceOrder.ts", "super(Guid, false);", "super(String, false);")
        rejectsActual("AllOrders.ts", "super(OrderView, true);", "super(Address, true);")
        rejectsActual("OrderById.ts", "new ParameterDescriptor('id', Guid, false)", "new ParameterDescriptor('id', String, false)")
        rejectsActual("OrderById.ts", "new ParameterDescriptor('id', Guid, false)", "new ParameterDescriptor('id', Guid, true)")
        rejectsActual("PlaceOrder.ts", "new PropertyDescriptor('requestedTime', TimeOnly, false)", "new PropertyDescriptor('requestedTime', String, false)")
        rejectsActual("OrderView.ts", "@field(DateOnly)", "@field(String)")
    }

    @Test
    fun `changed required parameter lists and collection envelopes fail`() {
        rejectsActual("OrderById.ts", "            'id',", "")
        rejectsActual("OrderById.ts", "            'id',", "            'id', 'id',")
        rejectsActual("AllOrders.ts", "extends QueryFor<OrderView[]>", "extends QueryFor<OrderView>")
        rejectsActual("AllOrders.ts", "static use(): [QueryResultWithState<OrderView[]>", "static use(): [QueryResultWithState<OrderView>")
    }

    @Test
    fun `missing and duplicate contract members fail`() {
        rejectsActual("PlaceOrder.ts", "    quantity?: number;", "")
        rejectsActual("PlaceOrder.ts", "    quantity?: number;", "    quantity?: number;\n    quantity?: number;")
        rejectsActual("OrderById.ts", "        super(OrderView, false);", "        super(OrderView, false);\n        super(OrderView, false);")
    }

    @Test
    fun `captured semantic changes fail independently even after both checksums are renewed`() {
        val file = captured.resolve("$capturedPath/OrderById.ts")
        val original = file.readText()
        file.writeText(replaceOnce(original, "super(OrderView, false);", "super(Address, false);"))
        rehash(file)
        renewManifestChecksum(file, original.toByteArray(Charsets.UTF_8))
        val error = assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(error.message.orEmpty().contains("captured/OrderById.ts contract"), error.message)
    }

    @Test
    fun `capture checksum corruption fails before parsed comparisons`() {
        captured.resolve("$capturedPath/PlaceOrder.ts").appendText("\n")
        val error = assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(error.message.orEmpty().contains("Capture checksum"), error.message)
    }

    @Test
    fun `missing actual files fail`() {
        assertTrue(actual.resolve("$actualPath/OrderView.ts").delete())
        assertFileSetFailure()
    }

    @Test
    fun `extra actual files including duplicate basenames fail`() {
        val extra = actual.resolve("other/OrderView.ts")
        extra.parentFile.mkdirs()
        actual.resolve("$actualPath/OrderView.ts").copyTo(extra)
        assertFileSetFailure()
        assertTrue(extra.delete())
        actual.resolve("$actualPath/notes.txt").writeText("not TypeScript")
        assertFileSetFailure()
    }

    @Test
    fun `moving an artifact to a same basename directory fails`() {
        val original = actual.resolve("$actualPath/OrderView.ts")
        val relocated = actual.resolve("$actualPath/nested/OrderView.ts")
        relocated.parentFile.mkdirs()
        original.copyTo(relocated)
        assertTrue(original.delete())
        assertFileSetFailure()
    }

    @Test
    fun `undeclared captured files and manifest paths fail`() {
        val extra = captured.resolve("elsewhere/OrderView.ts")
        extra.parentFile.mkdirs()
        captured.resolve("$capturedPath/OrderView.ts").copyTo(extra)
        assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(extra.delete())
        val manifest = captured.resolve("capture-manifest.json")
        manifest.writeText(replaceOnce(manifest.readText(), "$capturedPath/Address.ts", "elsewhere/Address.ts"))
        val error = assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(error.message.orEmpty().contains("Declared capture paths"), error.message)
    }

    @Test
    fun `fixed source identities cannot be substituted with valid hashes`() {
        val file = actual.resolve("$actualPath/AllOrders.ts")
        file.writeText(replaceOnce(file.readText(), "Source: arc.kotlin.differential.fixture.OrderView.",
            "Source: arc.kotlin.differential.fixture.AllOrders."))
        val error = assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(error.message.orEmpty().contains("source identity"), error.message)
    }

    @Test
    fun `captured source identity is fixed even when capture checksums are renewed`() {
        val file = captured.resolve("$capturedPath/AllOrders.ts")
        val original = file.readBytes()
        file.writeText(replaceOnce(file.readText(), "Source: Arc.Kotlin.Differential.Fixture.OrderView.",
            "Source: Arc.Kotlin.Differential.Fixture.AllOrders."))
        renewManifestChecksum(file, original)
        val error = assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(error.message.orEmpty().contains("captured/AllOrders.ts source identity"), error.message)
    }

    @Test
    fun `model and enum full bytes remain enforced after a valid rehash`() {
        listOf("Address.ts", "OrderKind.ts").forEach { name ->
            val file = actual.resolve("$actualPath/$name")
            val original = file.readText()
            file.writeText(original + "\n")
            rehash(file)
            assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
            file.writeText(original)
        }
    }

    @Test
    fun `index exports cannot disappear or duplicate`() {
        rejectsActual("index.ts", "export * from './OrderView';", "")
        rejectsActual("index.ts", "export * from './OrderView';", "export * from './OrderView';\nexport * from './OrderView';")
    }

    private fun rejectsActual(name: String, before: String, after: String) {
        val file = actual.resolve("$actualPath/$name")
        val original = file.readText()
        file.writeText(replaceOnce(original, before, after))
        if (name != "index.ts") rehash(file)
        val error = assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(!error.message.orEmpty().contains("checksum"), "Mutation must reach the parsed contract: ${error.message}")
        file.writeText(original)
    }

    private fun assertFileSetFailure() {
        val error = assertThrows(AssertionError::class.java) { CapturedProxyContract.verify(captured, actual) }
        assertTrue(error.message.orEmpty().contains("JVM relative file set"), error.message)
    }

    private fun replaceOnce(text: String, before: String, after: String): String {
        assertEquals(1, Regex(Regex.escape(before)).findAll(text).count(), "Mutation anchor: $before")
        return text.replace(before, after)
    }

    private fun rehash(file: File) {
        val text = file.readText()
        val body = text.substringAfter('\n')
        file.writeText(text.substringBefore(". Hash: ") + ". Hash: " + sha256(body.toByteArray(Charsets.UTF_8)) + "\n" + body)
    }

    private fun renewManifestChecksum(file: File, original: ByteArray) {
        val manifest = captured.resolve("capture-manifest.json")
        manifest.writeText(replaceOnce(manifest.readText(), sha256(original), sha256(file.readBytes())))
    }

    private fun sha256(bytes: ByteArray): String = MessageDigest.getInstance("SHA-256").digest(bytes)
        .joinToString("") { "%02X".format(it) }
}
