// Copyright (c) Cratis. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.

package io.cratis.arc.gradle

import io.cratis.arc.artifacts.ArcArtifactManifest
import io.cratis.arc.json.ArcObjectMapper
import io.cratis.arc.metadata.ApiEndpointOptions
import io.cratis.arc.metadata.CommandDescriptor
import io.cratis.arc.metadata.EnumDescriptor
import io.cratis.arc.metadata.InterfaceDescriptor
import io.cratis.arc.metadata.PropertyDescriptor
import io.cratis.arc.metadata.QueryDescriptor
import io.cratis.arc.metadata.TypeDescriptor
import java.nio.file.Files
import java.nio.file.Path
import org.junit.jupiter.api.Assertions.assertEquals
import org.junit.jupiter.api.Assertions.assertFalse
import org.junit.jupiter.api.Assertions.assertThrows
import org.junit.jupiter.api.Assertions.assertTrue
import org.junit.jupiter.api.Test
import org.junit.jupiter.api.io.TempDir

internal class ProxyFileSuffixTest {
    @TempDir lateinit var root: Path

    private val model = TypeDescriptor("Model", "sample.models.Model", listOf("sample", "models"),
        listOf(PropertyDescriptor("status", "sample.models.Status"), PropertyDescriptor("external", "shared.External")))
    private val contract = InterfaceDescriptor("Contract", "sample.models.Contract", listOf("sample", "models"),
        listOf(PropertyDescriptor("model", model.fullyQualifiedName)))
    private val status = EnumDescriptor("Status", "sample.models.Status", listOf("sample", "models"))
    private val command = CommandDescriptor("Save", "sample.commands.Save",
        listOf(PropertyDescriptor("contract", contract.fullyQualifiedName)),
        location = listOf("sample", "commands"), responseTypeName = model.fullyQualifiedName)
    private val query = QueryDescriptor("all", model.fullyQualifiedName, model.fullyQualifiedName,
        fullyQualifiedName = "sample.models.Model.all", location = listOf("sample", "models"))
    private val artifacts = MergedArcArtifacts(listOf(command), listOf(query), listOf(model), listOf(status), listOf(contract))

    @Test
    fun `suffix changes only generated paths and imports, not exported names or routes`() {
        val plain = root.resolve("plain")
        val suffixed = root.resolve("suffixed")
        generate(plain, false)
        generate(suffixed, true)
        val names = listOf("commands/Save", "models/All", "models/Model", "models/Contract", "models/Status")
        names.forEach { name ->
            val original = Files.readString(plain.resolve("$name.ts"))
            val changed = Files.readString(suffixed.resolve("$name.proxy.ts"))
            assertFalse(Files.exists(suffixed.resolve("$name.ts")), name)
            assertTrue(changed.startsWith("// @generated by Cratis. Source: "), name)
            assertEquals(original.substringAfter('\n').replace(Regex("(?<=['/])(?:Save|All|Model|Contract|Status)(?=')")) {
                "${it.value}.proxy"
            }, changed.substringAfter('\n'), name)
        }
        val save = Files.readString(suffixed.resolve("commands/Save.proxy.ts"))
        assertTrue(save.contains("from '../models/Model.proxy'"), save)
        assertTrue(save.contains("from '../models/Contract.proxy'"), save)
        val modelText = Files.readString(suffixed.resolve("models/Model.proxy.ts"))
        assertTrue(modelText.contains("from './Status.proxy'"), modelText)
        assertTrue(modelText.contains("from '@acme/shared'"), modelText)
        assertFalse(modelText.contains("@acme/shared.proxy"), modelText)
        assertTrue(Files.readString(suffixed.resolve("models/All.proxy.ts")).contains("from './Model.proxy'"))
        assertEquals("export * from './All.proxy';\nexport * from './Contract.proxy';\nexport * from './Model.proxy';\nexport * from './Status.proxy';\n",
            Files.readString(suffixed.resolve("models/index.ts")))
        assertTrue(Files.exists(suffixed.resolve("commands/index.ts")))
        assertFalse(Files.exists(suffixed.resolve("commands/index.proxy.ts")))
    }

    @Test
    fun `both suffix transitions clean only generated files and preserve manual files and exports`() {
        val output = root.resolve("transitions")
        generate(output, false)
        val manual = output.resolve("models/Notes.ts")
        Files.writeString(manual, "// written by a person\n")
        val index = output.resolve("models/index.ts")
        Files.writeString(index, Files.readString(index) + "export * from './Notes';\n// retained comment\n")
        generate(output, true)
        assertFalse(Files.exists(output.resolve("models/Model.ts")))
        assertFalse(Files.exists(output.resolve("commands/Save.ts")))
        assertTrue(Files.exists(output.resolve("models/Model.proxy.ts")))
        assertTrue(Files.readString(index).contains("export * from './Notes';"))
        assertTrue(Files.readString(index).contains("// retained comment"))
        assertFalse(Files.readString(index).contains("export * from './Model';"))
        generate(output, false)
        assertFalse(Files.exists(output.resolve("models/Model.proxy.ts")))
        assertFalse(Files.exists(output.resolve("commands/Save.proxy.ts")))
        assertTrue(Files.exists(output.resolve("models/Model.ts")))
        assertTrue(Files.readString(index).contains("export * from './Model';"))
        assertFalse(Files.readString(index).contains("export * from './Model.proxy';"))
        assertTrue(Files.readString(index).contains("export * from './Notes';"))
        assertEquals("// written by a person\n", Files.readString(manual))
        val bytes = Files.readAllBytes(output.resolve("models/Model.ts"))
        generate(output, false)
        assertTrue(bytes.contentEquals(Files.readAllBytes(output.resolve("models/Model.ts"))))
    }

    @Test
    fun `suffix cannot overwrite a handwritten destination`() {
        val output = root.resolve("protected")
        Files.createDirectories(output.resolve("models"))
        val manual = output.resolve("models/Model.proxy.ts")
        Files.writeString(manual, "// manual\n")
        val failure = assertThrows(org.gradle.api.GradleException::class.java) { generate(output, true) }
        assertTrue(failure.message.orEmpty().contains("Refusing to overwrite hand-written TypeScript file"))
        assertEquals("// manual\n", Files.readString(manual))
    }

    @Test
    fun `CLI switch uses same renderer and validates boolean input`() {
        val manifestRoot = root.resolve("manifest/META-INF/cratis/arc")
        Files.createDirectories(manifestRoot)
        ArcObjectMapper.create().writeValue(manifestRoot.resolve("sample.json").toFile(),
            ArcArtifactManifest("Sample", commands = listOf(command), queries = listOf(query), types = listOf(model),
                interfaces = listOf(contract), enums = listOf(status)))
        val output = root.resolve("cli")
        val arguments = arrayOf("--manifest-classpath", root.resolve("manifest").toString(),
            "--output-directory", output.toString(), "--proxy-segments-to-skip", "1",
            "--package-to-npm", "shared=@acme/shared")
        GenerateArcProxiesCli.main(arguments + arrayOf("--use-proxy-file-suffix", "true"))
        assertTrue(Files.exists(output.resolve("models/Model.proxy.ts")))
        assertFalse(Files.exists(output.resolve("models/Model.ts")))
        GenerateArcProxiesCli.main(arguments)
        assertTrue(Files.exists(output.resolve("models/Model.ts")))
        assertFalse(Files.exists(output.resolve("models/Model.proxy.ts")))
        assertThrows(IllegalArgumentException::class.java) {
            GenerateArcProxiesCli.main(arguments + arrayOf("--use-proxy-file-suffix", "yes"))
        }
    }

    private fun generate(output: Path, suffix: Boolean) {
        TypeScriptProxyGenerator(artifacts, ProxyGenerationOptions(output.toFile(), ApiEndpointOptions(), true, 1,
            packageMappings = mapOf("shared" to "@acme/shared")), suffix).generate()
    }
}
