# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

spring.application.name=arc-java-chronicle-sample
cratis.arc.endpoints.segments-to-skip-for-route=5
cratis.arc.tenancy.resolvers=header
cratis.arc.tenancy.required=true
cratis.arc.tenancy.header-name=x-cratis-tenant-id
cratis.arc.tenancy.constrain-to-authenticated-claims=false
cratis.arc.command-scope-completion-timeout=30s
cratis.chronicle.event-store=ArcJavaChronicleSample
cratis.chronicle.default-sink-type-id=InMemory
cratis.chronicle.namespace-resolution.strategy=fixed
cratis.chronicle.namespace=Default
