// @generated by Cratis. Source: Arc.Kotlin.Differential.Fixture.Address. Hash: 7A9B89A9041767F925424381EEB125C22FE4DA4B79CA933C6247F62BBAE071D2
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';

export class Address {
    @field(String)
    street!: string;
    @field(String)
    city!: string;
}
