// @generated by Cratis. Source: Arc.Kotlin.Differential.Fixture.OrderView. Hash: 234E98DB644DDEF9D2EB26BAA86B01691053762F96BD034943536AF149877A60
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, Sorting, Paging } from '@cratis/arc/queries';
import { useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging, PerformQuery, SetSorting, SetPage, SetPageSize, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { OrderView } from './OrderView';

class AllOrdersSortBy {

    constructor(readonly query: AllOrders) {
    }

}

class AllOrdersSortByWithoutQuery {

}


export class AllOrders extends QueryFor<OrderView[]> {
    readonly route: string = '/api/arc/kotlin/differential/fixture/all-orders';
    readonly queryName: string = 'Arc.Kotlin.Differential.Fixture.OrderView.AllOrders';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: OrderView[] = [];
    private readonly _sortBy: AllOrdersSortBy;
    private static readonly _sortBy: AllOrdersSortByWithoutQuery = new AllOrdersSortByWithoutQuery();

    constructor() {
        super(OrderView, true);
        this._sortBy = new AllOrdersSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];


    get sortBy(): AllOrdersSortBy {
        return this._sortBy;
    }

    static get sortBy(): AllOrdersSortByWithoutQuery {
        return this._sortBy;
    }

    static use(sorting?: Sorting): [QueryResultWithState<OrderView[]>, PerformQuery, SetSorting] {
        return useQuery<OrderView[], AllOrders>(AllOrders, undefined, sorting);
    }

    static useWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<OrderView[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<OrderView[], AllOrders>(AllOrders, new Paging(0, pageSize), undefined, sorting);
    }

    static useSuspense(sorting?: Sorting): [QueryResultWithState<OrderView[]>, PerformQuery, SetSorting] {
        return useSuspenseQuery<OrderView[], AllOrders>(AllOrders, undefined, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, sorting?: Sorting): [QueryResultWithState<OrderView[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<OrderView[], AllOrders>(AllOrders, new Paging(0, pageSize), undefined, sorting);
    }

    static when(condition: boolean): QueryWhen<AllOrders, OrderView[]> {
        return new QueryWhen<AllOrders, OrderView[]>(AllOrders, condition);
    }
}
