// @generated by Cratis. Source: Arc.Kotlin.Differential.Fixture.OrderView. Hash: 36394FA825FBE1741AC936969B8B9784A601E6400F539C891FD5F8CE178C7F39
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { Guid } from '@cratis/fundamentals';
import { OrderView } from './OrderView';


export interface OrderByIdParameters {
    id: Guid;
}


export class OrderById extends QueryFor<OrderView, OrderByIdParameters> {
    readonly route: string = '/api/arc/kotlin/differential/fixture/order-by-id';
    readonly queryName: string = 'Arc.Kotlin.Differential.Fixture.OrderView.OrderById';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: OrderView = {} as any;

    constructor() {
        super(OrderView, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'id',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('id', Guid, false),
    ];

    id!: Guid;


    static use(args?: OrderByIdParameters): [QueryResultWithState<OrderView>, PerformQuery<OrderByIdParameters>, SetSorting] {
        return useQuery<OrderView, OrderById, OrderByIdParameters>(OrderById, args);
    }

    static useSuspense(args?: OrderByIdParameters): [QueryResultWithState<OrderView>, PerformQuery<OrderByIdParameters>, SetSorting] {
        return useSuspenseQuery<OrderView, OrderById, OrderByIdParameters>(OrderById, args);
    }

    static when(condition: boolean): QueryWhen<OrderById, OrderView, OrderByIdParameters> {
        return new QueryWhen<OrderById, OrderView, OrderByIdParameters>(OrderById, condition);
    }
}
