// @generated by Cratis. Source: Arc.Kotlin.Differential.Fixture.OrderView. Hash: 70C6E2A0FD0011F3C2013673B7CBCE68B02E54FF0D83017F63A5CA0609A2943E
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { DateOnly } from '@cratis/fundamentals';
import { Guid } from '@cratis/fundamentals';
import { TimeOnly } from '@cratis/fundamentals';
import { Address } from './Address';
import { OrderKind } from './OrderKind';

export class OrderView {
    @field(Guid)
    id!: Guid;
    @field(String)
    customer!: string;
    @field(Number)
    kind!: OrderKind;
    @field(DateOnly)
    requestedDate!: DateOnly;
    @field(TimeOnly)
    requestedTime!: TimeOnly;
    @field(Address)
    shipTo!: Address;
}
