// @generated by Cratis. Source: Arc.Kotlin.Differential.Fixture.OrderKind. Hash: 129408C05C9E221C4B2501E17B9B99DB53CC3F8B5885A1F367F66B0213A1BB1D
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
export enum OrderKind {
    standard = 0,
    express = 1,
}
