// @generated by Cratis. Source: Arc.Kotlin.Differential.Fixture.PlaceOrder. Hash: C8FBD825CF1B65EF2F60E2652F64AF20E8A18488CA91F4081B0B8EF6BB4E7B19
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
/* eslint-disable @typescript-eslint/no-empty-interface */
// eslint-disable-next-line header/header
import { Command } from '@cratis/arc/commands';
import { useCommand, SetCommandValues, ClearCommandValues } from '@cratis/arc.react/commands';
import { PropertyDescriptor } from '@cratis/arc/reflection';
import { Address } from './Address';
import { OrderKind } from './OrderKind';
import { Guid } from '@cratis/fundamentals';
import { DateOnly } from '@cratis/fundamentals';
import { TimeOnly } from '@cratis/fundamentals';

export interface IPlaceOrder {
    customer?: string;
    express?: boolean;
    id?: Guid;
    kind?: OrderKind;
    placedAt?: Date;
    quantity?: number;
    requestedDate?: DateOnly;
    requestedTime?: TimeOnly;
    shipTo?: Address;
    tags?: string[];
}


export class PlaceOrder extends Command<IPlaceOrder, Guid> implements IPlaceOrder {
    readonly route: string = '/api/arc/kotlin/differential/fixture/place-order';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly propertyDescriptors: PropertyDescriptor[] = [
        new PropertyDescriptor('customer', String, false),
        new PropertyDescriptor('express', Boolean, false),
        new PropertyDescriptor('id', Guid, false),
        new PropertyDescriptor('kind', Number, false),
        new PropertyDescriptor('placedAt', Date, false),
        new PropertyDescriptor('quantity', Number, false),
        new PropertyDescriptor('requestedDate', DateOnly, false),
        new PropertyDescriptor('requestedTime', TimeOnly, false),
        new PropertyDescriptor('shipTo', Address, false),
        new PropertyDescriptor('tags', String, false),
    ];

    private _customer!: string;
    private _express!: boolean;
    private _id!: Guid;
    private _kind!: OrderKind;
    private _placedAt!: Date;
    private _quantity!: number;
    private _requestedDate!: DateOnly;
    private _requestedTime!: TimeOnly;
    private _shipTo!: Address;
    private _tags!: string[];

    constructor() {
        super(Guid, false);
    }

    get requestParameters(): string[] {
        return [
        ];
    }

    get customer(): string {
        return this._customer;
    }

    set customer(value: string) {
        this._customer = value;
        this.propertyChanged('customer');
    }
    get express(): boolean {
        return this._express;
    }

    set express(value: boolean) {
        this._express = value;
        this.propertyChanged('express');
    }
    get id(): Guid {
        return this._id;
    }

    set id(value: Guid) {
        this._id = value;
        this.propertyChanged('id');
    }
    get kind(): OrderKind {
        return this._kind;
    }

    set kind(value: OrderKind) {
        this._kind = value;
        this.propertyChanged('kind');
    }
    get placedAt(): Date {
        return this._placedAt;
    }

    set placedAt(value: Date) {
        this._placedAt = value;
        this.propertyChanged('placedAt');
    }
    get quantity(): number {
        return this._quantity;
    }

    set quantity(value: number) {
        this._quantity = value;
        this.propertyChanged('quantity');
    }
    get requestedDate(): DateOnly {
        return this._requestedDate;
    }

    set requestedDate(value: DateOnly) {
        this._requestedDate = value;
        this.propertyChanged('requestedDate');
    }
    get requestedTime(): TimeOnly {
        return this._requestedTime;
    }

    set requestedTime(value: TimeOnly) {
        this._requestedTime = value;
        this.propertyChanged('requestedTime');
    }
    get shipTo(): Address {
        return this._shipTo;
    }

    set shipTo(value: Address) {
        this._shipTo = value;
        this.propertyChanged('shipTo');
    }
    get tags(): string[] {
        return this._tags;
    }

    set tags(value: string[]) {
        this._tags = value;
        this.propertyChanged('tags');
    }

    static use(initialValues?: IPlaceOrder): [PlaceOrder, SetCommandValues<IPlaceOrder>, ClearCommandValues] {
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        return useCommand<PlaceOrder, IPlaceOrder>(PlaceOrder, initialValues);
    }
}
