// @generated by Cratis. Source: differential.fixture.models.FixtureModel
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { FixtureModel } from './FixtureModel';


export interface ByIdParameters {
    identifier: string;
}


export class ById extends QueryFor<FixtureModel, ByIdParameters> {
    readonly route: string = '/api/models/by-id';
    readonly queryName: string = 'differential.fixture.models.FixtureModel.byId';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: FixtureModel = {} as any;

    constructor() {
        super(FixtureModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
            'identifier',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('identifier', String, false),
    ];

    identifier!: string;


    static use(args?: ByIdParameters): [QueryResultWithState<FixtureModel>, PerformQuery<ByIdParameters>, SetSorting] {
        return useQuery<FixtureModel, ById, ByIdParameters>(ById, args);
    }

    static useSuspense(args?: ByIdParameters): [QueryResultWithState<FixtureModel>, PerformQuery<ByIdParameters>, SetSorting] {
        return useSuspenseQuery<FixtureModel, ById, ByIdParameters>(ById, args);
    }

    static when(condition: boolean): QueryWhen<ById, FixtureModel, ByIdParameters> {
        return new QueryWhen<ById, FixtureModel, ByIdParameters>(ById, condition);
    }
}
