// @generated by Cratis. Source: differential.fixture.models.Circle
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field, derivedType } from '@cratis/fundamentals';
import { ShapeBase } from './ShapeBase';

@derivedType('circle')
export class Circle extends ShapeBase {
    @field(String)
    displayName!: string;
    @field(Number)
    radius!: number;
}
