// @generated by Cratis. Source: differential.fixture.models.FixturePermissions
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
export enum FixturePermissions {
    none = 0,
    read = 1,
    write = 2,
}

export const allFixturePermissions = FixturePermissions.read | FixturePermissions.write;
