// @generated by Cratis. Source: differential.fixture.models.FixtureModel
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from "@cratis/fundamentals";
import type { FixturePermissions } from "./FixturePermissions";
import type { FixtureState } from "./FixtureState";

export class FixtureModel {
   @field(String)
   identifier!: string;
   @field(Object)
   labelsByCategory!: Record<string, string>;
   @field(Number)
   permissions!: FixturePermissions;
   @field(Number)
   state!: FixtureState;
   @field(Date)
   updatedAt!: Date;
}
