// @generated by Cratis. Source: differential.fixture.models.FixtureState
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

// eslint-disable-next-line header/header
export enum FixtureState {
    new = 0,
    active = 17,
}
