// @generated by Cratis. Source: differential.fixture.models.EmptyModel
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { EmptyModel } from './EmptyModel';



export class GetEmpty extends QueryFor<EmptyModel> {
    readonly route: string = '/api/models/get-empty';
    readonly queryName: string = 'differential.fixture.models.EmptyModel.getEmpty';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: EmptyModel = {} as any;

    constructor() {
        super(EmptyModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<EmptyModel>, PerformQuery, SetSorting] {
        return useQuery<EmptyModel, GetEmpty>(GetEmpty);
    }

    static useSuspense(): [QueryResultWithState<EmptyModel>, PerformQuery, SetSorting] {
        return useSuspenseQuery<EmptyModel, GetEmpty>(GetEmpty);
    }

    static when(condition: boolean): QueryWhen<GetEmpty, EmptyModel> {
        return new QueryWhen<GetEmpty, EmptyModel>(GetEmpty, condition);
    }
}
