// @generated by Cratis. Source: differential.fixture.models.ShapeHolder
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useQuery, useSuspenseQuery, PerformQuery, SetSorting, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { ShapeHolder } from './ShapeHolder';



export class GetShapes extends QueryFor<ShapeHolder> {
    readonly route: string = '/api/models/get-shapes';
    readonly queryName: string = 'differential.fixture.models.ShapeHolder.getShapes';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: ShapeHolder = {} as any;

    constructor() {
        super(ShapeHolder, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<ShapeHolder>, PerformQuery, SetSorting] {
        return useQuery<ShapeHolder, GetShapes>(GetShapes);
    }

    static useSuspense(): [QueryResultWithState<ShapeHolder>, PerformQuery, SetSorting] {
        return useSuspenseQuery<ShapeHolder, GetShapes>(GetShapes);
    }

    static when(condition: boolean): QueryWhen<GetShapes, ShapeHolder> {
        return new QueryWhen<GetShapes, ShapeHolder>(GetShapes, condition);
    }
}
