// @generated by Cratis. Source: differential.fixture.models.FixtureModel
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState } from '@cratis/arc/queries';
import { useObservableQuery, useSuspenseObservableQuery, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { FixtureModel } from './FixtureModel';



export class ObserveOne extends ObservableQueryFor<FixtureModel> {
    readonly route: string = '/api/models/observe-one';
    readonly queryName: string = 'differential.fixture.models.FixtureModel.observeOne';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: FixtureModel = {} as any;

    constructor() {
        super(FixtureModel, false);
    }

    get requiredRequestParameters(): string[] {
        return [
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
    ];



    static use(): [QueryResultWithState<FixtureModel>] {
        const [result] = useObservableQuery<FixtureModel, ObserveOne>(ObserveOne);
        return [result];
    }

    static useSuspense(): [QueryResultWithState<FixtureModel>] {
        const [result] = useSuspenseObservableQuery<FixtureModel, ObserveOne>(ObserveOne);
        return [result];
    }

    static when(condition: boolean): ObservableQueryWhen<ObserveOne, FixtureModel> {
        return new ObservableQueryWhen<ObserveOne, FixtureModel>(ObserveOne, condition);
    }
}
