// @generated by Cratis. Source: differential.fixture.models.FixtureModel
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { ObservableQueryFor, QueryResultWithState, Sorting, SortingActions, SortingActionsForObservableQuery, Paging, type ChangeSet } from '@cratis/arc/queries';
import { useObservableQuery, useObservableQueryWithPaging, useSuspenseObservableQuery, useSuspenseObservableQueryWithPaging, useChangeStream, type SetSorting, type SetPage, type SetPageSize, ObservableQueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { FixtureModel } from './FixtureModel';

class ObserveSortBy {
    private _filter: SortingActionsForObservableQuery<FixtureModel[]>;

    constructor(readonly query: Observe) {
        this._filter = new SortingActionsForObservableQuery<FixtureModel[]>('filter', query);
    }

    get filter(): SortingActionsForObservableQuery<FixtureModel[]> {
        return this._filter;
    }
}

class ObserveSortByWithoutQuery {
    private _filter: SortingActions  = new SortingActions('filter');

    get filter(): SortingActions {
        return this._filter;
    }
}

export interface ObserveParameters {

    filter: string;
}


export class Observe extends ObservableQueryFor<FixtureModel[], ObserveParameters> {
    readonly route: string = '/api/models/observe';
    readonly queryName: string = 'differential.fixture.models.FixtureModel.observe';
    readonly treatWarningsAsErrors: boolean = false;
    readonly roles: string[] = [];
    readonly defaultValue: FixtureModel[] = [];
    private readonly _sortBy: ObserveSortBy;
    private static readonly _sortBy: ObserveSortByWithoutQuery = new ObserveSortByWithoutQuery();

    constructor() {
        super(FixtureModel, true);
        this._sortBy = new ObserveSortBy(this);
    }

    get requiredRequestParameters(): string[] {
        return [
            'filter',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('filter', String, false),
    ];

    filter!: string;

    get sortBy(): ObserveSortBy {
        return this._sortBy;
    }

    static get sortBy(): ObserveSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, SetSorting] {
        return useObservableQuery<FixtureModel[], Observe, ObserveParameters>(Observe, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, SetSorting, SetPage, SetPageSize] {
        return useObservableQueryWithPaging<FixtureModel[], Observe>(Observe, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, SetSorting] {
        return useSuspenseObservableQuery<FixtureModel[], Observe, ObserveParameters>(Observe, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: ObserveParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, SetSorting, SetPage, SetPageSize] {
        return useSuspenseObservableQueryWithPaging<FixtureModel[], Observe>(Observe, new Paging(0, pageSize), args, sorting);
    }

    static useChangeStream(args?: ObserveParameters, getKey?: (item: FixtureModel) => unknown, sorting?: Sorting): ChangeSet<FixtureModel> {
        return useChangeStream<FixtureModel, Observe, ObserveParameters>(Observe, args, getKey, sorting);
    }

    static when(condition: boolean): ObservableQueryWhen<Observe, FixtureModel[], ObserveParameters> {
        return new ObservableQueryWhen<Observe, FixtureModel[], ObserveParameters>(Observe, condition);
    }
}
