// @generated by Cratis. Source: differential.fixture.models.FixtureModel
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { QueryFor, QueryResultWithState, Sorting, SortingActions, SortingActionsForQuery, Paging, QueryHttpMethod } from '@cratis/arc/queries';
import { useQuery, useQueryWithPaging, useSuspenseQuery, useSuspenseQueryWithPaging, PerformQuery, SetSorting, SetPage, SetPageSize, QueryWhen } from '@cratis/arc.react/queries';
import { ParameterDescriptor } from '@cratis/arc/reflection';
import { FixtureModel } from './FixtureModel';

class SearchSortBy {
    private _filter: SortingActionsForQuery<FixtureModel[]>;
    private _labels: SortingActionsForQuery<FixtureModel[]>;

    constructor(readonly query: Search) {
        this._filter = new SortingActionsForQuery<FixtureModel[]>('filter', query);
        this._labels = new SortingActionsForQuery<FixtureModel[]>('labels', query);
    }

    get filter(): SortingActionsForQuery<FixtureModel[]> {
        return this._filter;
    }
    get labels(): SortingActionsForQuery<FixtureModel[]> {
        return this._labels;
    }
}

class SearchSortByWithoutQuery {
    private _filter: SortingActions  = new SortingActions('filter');
    private _labels: SortingActions  = new SortingActions('labels');

    get filter(): SortingActions {
        return this._filter;
    }
    get labels(): SortingActions {
        return this._labels;
    }
}

export interface SearchParameters {
    filter: string;
    labels?: string[];
}


export class Search extends QueryFor<FixtureModel[], SearchParameters> {
    readonly route: string = '/custom/fixture-search';
    readonly queryName: string = 'differential.fixture.models.FixtureModel.search';
    readonly treatWarningsAsErrors: boolean = true;
    readonly roles: string[] = ['viewer', 'auditor'];
    readonly defaultValue: FixtureModel[] = [];
    private readonly _sortBy: SearchSortBy;
    private static readonly _sortBy: SearchSortByWithoutQuery = new SearchSortByWithoutQuery();

    constructor() {
        super(FixtureModel, true);
        this._sortBy = new SearchSortBy(this);
        this.setHttpMethod(QueryHttpMethod.Query);
    }

    get requiredRequestParameters(): string[] {
        return [
            'filter',
        ];
    }

    readonly parameterDescriptors: ParameterDescriptor[] = [
        new ParameterDescriptor('filter', String, false),
        new ParameterDescriptor('labels', String, true),
    ];

    filter!: string;
    labels!: string[];

    get sortBy(): SearchSortBy {
        return this._sortBy;
    }

    static get sortBy(): SearchSortByWithoutQuery {
        return this._sortBy;
    }

    static use(args?: SearchParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, PerformQuery<SearchParameters>, SetSorting] {
        return useQuery<FixtureModel[], Search, SearchParameters>(Search, args, sorting);
    }

    static useWithPaging(pageSize: number, args?: SearchParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useQueryWithPaging<FixtureModel[], Search>(Search, new Paging(0, pageSize), args, sorting);
    }

    static useSuspense(args?: SearchParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, PerformQuery<SearchParameters>, SetSorting] {
        return useSuspenseQuery<FixtureModel[], Search, SearchParameters>(Search, args, sorting);
    }

    static useSuspenseWithPaging(pageSize: number, args?: SearchParameters, sorting?: Sorting): [QueryResultWithState<FixtureModel[]>, PerformQuery, SetSorting, SetPage, SetPageSize] {
        return useSuspenseQueryWithPaging<FixtureModel[], Search>(Search, new Paging(0, pageSize), args, sorting);
    }

    static when(condition: boolean): QueryWhen<Search, FixtureModel[], SearchParameters> {
        return new QueryWhen<Search, FixtureModel[], SearchParameters>(Search, condition);
    }
}
