// @generated by Cratis. Source: differential.fixture.models.ShapeHolder
/*---------------------------------------------------------------------------------------------
 *  **DO NOT EDIT** - This file is an automatically generated file.
 *--------------------------------------------------------------------------------------------*/

/* eslint-disable sort-imports */
// eslint-disable-next-line header/header
import { field } from '@cratis/fundamentals';
import { Circle } from './Circle';
import { Shape } from '../Contracts/Shape';

export class ShapeHolder {
    @field(Shape, true, [Circle])
    shapes!: Shape[];
}
