# Copyright (c) Cratis. All rights reserved.
# Licensed under the MIT license. See LICENSE file in the project root for full license information.

name: Verify Semver Label

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled, unlabeled]
    branches:
      - main

permissions:
  contents: read

jobs:
  verify:
    uses: Cratis/Workflows/.github/workflows/verify-release-intent.yml@6a5e4f4b293e4b0854d348549d9a9f01255e42d2 # main
